services: # The containers we are going to run
  websocket-server:
    build:
      context: ./AAAASS
      dockerfile: Dockerfile
    container_name: websocket-server
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network

networks: # All the networks that connects our containers
  app-network:
    driver: bridge