services: # The containers we are going to run
  websocket-server2:
    build:
      context: ./AAAASS
      dockerfile: Dockerfile
    container_name: websocket-server2
    restart: unless-stopped
    ports:
      - "8900:8090"
    networks:
      - app-network

networks: # All the networks that connects our containers
  app-network:
    driver: bridge